[build]
  publish   = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/api/widgets"
  to = "/.netlify/functions/widgets"
  status = 200
